### ISSUE TITLE
Cannot read property 'initialMode' of undefined

### ISSUE THREAD

**Issue by rishimukherjee** [codemotionapps/react-native-dark-mode#24]
I am getting the following error:

`Cannot read property 'initialMode' of undefined`.

I am just importing 

`import { useDarkMode } from 'react-native-dark-mode';`

then calling

`const isDarkMode = useDarkMode();`

It gives me this error. I am on React Native 0.60.4 and react-native-dark-mode 0.1.2.

**Comment by DimitarNestorov** [comment]
That's strange. `initialMode` isn't pascal case. I need more information. Does this happen on Android only or on iOS only or both? If it's only iOS did you run pod install after `npm install`/`yarn add`?

**Comment by rishimukherjee** [comment]
Sorry, I updated it to camelCase. So, this error is in iOS and not in android. 

After I saw your reply, I did a pod install and it worked. Do you want me to make a pull request to update the doc in the Readme for this?

**Comment by cesargdm** [comment]
I had to add your library to the transformIgnorePatterns since `export` was being unrecognized

<img width="827" alt="Screen Shot 2020-04-04 at 14 52 10" src="https://user-images.githubusercontent.com/10179494/78461156-e4d24400-7683-11ea-968a-c684bca13f18.png">


<img width="816" alt="Screen Shot 2020-04-04 at 14 47 37" src="https://user-images.githubusercontent.com/10179494/78461035-3d551180-7683-11ea-9957-b7e7e337b5fd.png">

**Comment by cesargdm** [comment]
https://github.com/facebook/jest/issues/2550
