### ISSUE TITLE
Setting the value of `mode` in` DarkModeProvider` has no effect.

### ISSUE THREAD

**Issue by kimmy-wang** [codemotionapps/react-native-dark-mode#48]
I set the value of `mode` in` DarkModeProvider`, it has no effect.

[repo](https://github.com/cwamp/cwamp-rn)

**Comment by DimitarNestorov** [comment]
![Screen Recording 2020-03-01 at 7 03 30 AM](https://user-images.githubusercontent.com/8790386/75619922-f4450580-5b8a-11ea-8947-ea4b000f207e.gif)
Are you sure? I just ran it and it seems to be working fine.

**Comment by kimmy-wang** [comment]
But the background color of the main page has not changed.

**Comment by DimitarNestorov** [comment]
That's because you're using `<DarkModeProvider>` in the same place you're already calling hooks. You have two options:
1. Extract anything but the `<DarkModeProvider>` and `currentMode` from the App component in a separate component and call the other hooks there
2. Just use `currentMode` instead of the hooks like so:
```javascript
const styles = dynamicStyleSheet[currentMode];
const source = logoUri[currentMode];
const modeSource = modeUri[currentMode];
const barSource = barStyle[currentMode];
const barBGSource = barBGStyle[currentMode];
```
![Screen Recording 2020-03-01 at 5 57 59 PM](https://user-images.githubusercontent.com/8790386/75628983-bd044200-5be6-11ea-8c38-9acae59ac5d2.gif)

Hooks are going to work fine in child components either way.
